### ISSUE TITLE
`LBJavaSerializationTest` should be fixed 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/saul#200]
[`LBJavaSerializationTest`](https://github.com/IllinoisCogComp/saul/blob/master/saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/LBJavaSerializationTest.scala) has some issues and it is mostly commented out now. 
If you run it the first time it will fail, but if you run it for the 2nd or more times it will pass the test. (since it has created an output already in the first run.)

Any ideas how to make it work, even for the first test run?

**Comment by bhargav** [comment]
This test failure does not seem to happen now. Closing the issue.

**Comment by danyaljj** [comment]
Hmmm ... it's because its commented: 
https://github.com/IllinoisCogComp/saul/blob/master/saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/LBJavaSerializationTest.scala

**Comment by bhargav** [comment]
Ah. My bad. I should have checked the code.
