### ISSUE TITLE
Change all T<:AnyRef to Any

### ISSUE THREAD

**Issue by kordjamshidi** [IllinoisCogComp/saul#256]
This would give us flexibility and less technical problems for type inconsistencies I think. Also probably would solve my problem in issue #253. @sameersingh , I remember you suggested this change before, should we do it now?

**Comment by danyaljj** [comment]
@kordjamshidi do think this is still an issue?

**Comment by kordjamshidi** [comment]
For now it is not a problem, later we can revisit this issue and decide. We can close it now.
