### ISSUE TITLE
on testing the constrained classifiers 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/saul#294]
I'm arguing that [this line in `test` function of the `ConstrainedClassifier`](https://github.com/IllinoisCogComp/saul/blob/master/saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala#L146) creates conceptual issues for testing constrained classifiers. 

Consider the output of two lines from ER example: 
```scala 
    println("PerConstrainedClassifier.pathToHead.get.to.getTestingInstances =  " + PerConstrainedClassifier.pathToHead.get.to.getTestingInstances.size)
    println("tokens.getTestingInstances.size =  " + tokens.getTestingInstances.size)
```

```
[info] PerConstrainedClassifier.pathToHead.get.to.getTestingInstances =  969
[info] tokens.getTestingInstances.size =  63168
```

this means that if you use `pathToHead` the number of the instances that you'd get is much smaller that the original test size (969 is suspiciously small; there might be a bug somewhere ... ). Hence testing on the result of `pathToHead` is not realistic. Therefore, we should never use it in the testing (hence always use `clf.node.getTestingInstances`).

**Comment by kordjamshidi** [comment]
oh this was relevant to my last issue indeed about disconnected nodes, #400
