### ISSUE TITLE
Using LoadClassifier with OnClassifier of the ConstrainedClassifiers

### ISSUE THREAD

**Issue by kordjamshidi** [IllinoisCogComp/saul#334]
Load works with Learnable, onClassifier can not be casted to Learnable (right?) so it seems we should use the load helpers from the original Learner from Lbjava then to load models into ConstrainedClassifiers? Any ideas? Should we overload `load` to get a list of `Learner` as well?

**Comment by danyaljj** [comment]
I think same as #352
