### ISSUE TITLE
Using the latest Edison 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/saul#339]
When updating to the latest version of Edison, some of the SRL tests fail (which might be due to some recent changes in Edison). I think we figure our where the issues are and upgrade to the latest Edison version.

**Comment by danyaljj** [comment]
to simulate the issue change `cogcompNLPVersion` to "3.0.42" and run `testOnly *DataModelTest` and/or ` testOnly *ConstraintsTest`

**Comment by christos-c** [comment]
The main reason I see for the failures is the issue I open [here](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/issues/143): `DummyTextAnnotationGenerator` is now generating only multi-sentence TAs so all the equality chekcs designed for the single sentence fail.

**Comment by danyaljj** [comment]
This is done in #370
