### ISSUE TITLE
Extend the number of accessible learning algorithms 

### ISSUE THREAD

**Issue by kordjamshidi** [IllinoisCogComp/saul#368]
WEKA is a dependency in Lbjava and I guess there should be an interface in there. Can we make some techniques accessible from there in Saul too? (specifically decision trees and rule-based models)

**Comment by bhargav** [comment]
Good idea. Will check out how Weka is being used in LBJava.

**Comment by danyaljj** [comment]
As far as I know the Weka wrapper in lbjava is outdated and I found it complicated to use. Unfortunately we don't have much documentation on its usage. If you figure out how to use it, adding some usage example to lbjava as well would be very helpful.

**Comment by kordjamshidi** [comment]
Ok, let @bhargav take a look then, we can always ask Nick to help if this is too complicated.

**Comment by kordjamshidi** [comment]
@bhargav any findings on this?

**Comment by kordjamshidi** [comment]
Probably you have seen this, but if not https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/doc/LBJLIBRARY.md#5210-learnwekawrapper.

**Comment by bhargav** [comment]
I looked at the documentation in LBJava. Will have to try out a few examples. Will update my finding in a couple of days.

**Comment by bhargav** [comment]
So the WekaWrapper in LBJava currently only supports discrete, categorical, real (Weka also seems to have Date and Relational features http://weka.sourceforge.net/doc.dev/weka/core/Attribute.html )

We will have to manually provide an attribute string which is a representation for each feature name, its type and values (for categorical). I'll try generating this attribute string for the spam example and see if it works seamlessly.

**Comment by bhargav** [comment]
A better WekaWrapper was added to Saul. Closing this issue as fixed.
