### ISSUE TITLE
Update the scores of the ER example 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/saul#396]
Some changes were made to the ER  node classes hashcodes/identifiers in #395 which might potentially change the scores. Re-run the constrained classifiers and report the scores.

**Comment by bhargav** [comment]
We should use something like https://github.com/tpolecat/tut to add executable scala code to the markdown files and have it run the app from classifier and update documentation programmatically. 💯

**Comment by danyaljj** [comment]
Only if we could check in the data into the repo,

**Comment by danyaljj** [comment]
Or have programmatic way of loading/downloading the data.
