### ISSUE TITLE
try to configure the project on c9

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [IllinoisCogComp/saul#418]
c9.io

**Comment by Xuefeng-Zhu** [comment]
@danyaljj I have successfully set up saul on c9 https://ide.c9.io/xuefeng_zhu/saul

**Comment by Xuefeng-Zhu** [comment]
It seems that there is no way to clone a shared project

**Comment by danyaljj** [comment]
hmm ... I tried to register but it keeps asking us for username password. Let's see it altogether later today?

**Comment by Xuefeng-Zhu** [comment]
Sure
