### ISSUE TITLE
g8

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/saul#425]
g8 is a fast way of creating templates for projects. 
https://github.com/foundweekends/giter8

an example usage is explained in Wolfe: 
https://github.com/wolfe-pack/wolfe

**Comment by bhargav** [comment]
Made this repository for the sample task template:
https://github.com/bhargav/saul.g8

Usage (after setting up g8 tool):
```
g8 bhargav/saul.g8
```

If the example looks fine, we can move it to the IllinoisCogComp organization and add documentation.

**Comment by danyaljj** [comment]
Example looks nice! Documentation would be great! 
And I think you can move it to the organization repo.
