### ISSUE TITLE
SRL readme: clarification needed

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/saul#429]
So [here in the readme](https://github.com/danyaljj/saul-1/tree/srl-cleanup/saul-examples/src/main/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling#second-phase-test-independent-models) it says: 

```
-[x] [aTs] Test aTr, bTr, cTr, dTr, eTr, fTr, gTr independently. -aTr with constraints.
```

How should I interpret this?

**Comment by kordjamshidi** [comment]
remove this `-[x] [aTs] Test aTr, bTr, cTr, dTr, eTr, fTr, gTr independently. `

**Comment by kordjamshidi** [comment]
if you are working on the SRL documentation make one PR for it and better not to spread various  issues and PRs.

**Comment by danyaljj** [comment]
No I just need to understand how constrained models are evaluated ...

**Comment by kordjamshidi** [comment]
ok, I saw you had minor edits on the documentation in #428 , thought this is related to the same PR.

**Comment by danyaljj** [comment]
As a more broad question, I wanted to evaluate the performance of [current constrained classifiers in SRL](https://github.com/IllinoisCogComp/saul/blob/master/saul-examples/src/main/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/SRLConstrainedClassifiers.scala), which I think only one of them (`argTypeConstraintClassifier`) is being used.  

Do we have an existing evaluation corresponding to `argTypeConstraintClassifier` classifier?
Is it this "aTs" in [this line](https://github.com/IllinoisCogComp/saul/tree/master/saul-examples/src/main/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling#second-phase-test-independent-models)?

**Comment by kordjamshidi** [comment]
You see the variations of aTr, cTr and fTr and you see they have been experimented with L+I models i.e. using the constraints. And, yes, the line that you point is aTr with constraints.

**Comment by kordjamshidi** [comment]
Also, please see my above comment this line should be removed `-[x] [aTs] Test aTr, bTr, cTr, dTr, eTr, fTr, gTr independently`. It has been left there from the primary schedule, but then each table comes with the description like `-aTr with constraints`.
