### ISSUE TITLE
Logger error when testing

### ISSUE THREAD

**Issue by kordjamshidi** [IllinoisCogComp/saul#433]
I think we had this before, and now it pops up again for me in my new experiment.  `LoggerFactory is not a Logback LoggerContext because another Logger implementation(class org.slf4j.impl.Log4jLoggerFactory) in the classpath is used as default Logger.
So, cannot perform 'isLevelDebug'.`

**Comment by kordjamshidi** [comment]
@Rahgooy : I don't remember how you solved this for SpRL testing and why that fix does not work here.

**Comment by Rahgooy** [comment]
@kordjamshidi , it just reports the error and continues the work, isn't it?
The error says that it can't change the level of logging because the selected logger type is not supporting it.

**Comment by kordjamshidi** [comment]
no, it does not continue. It throws an exception that i primarily thought it is related to this message. But let me check.

**Comment by kordjamshidi** [comment]
Ok, the error is for a different reason. Thanks @Rahgooy .
