### ISSUE TITLE
Gurobi ?

### ISSUE THREAD

**Issue by kordjamshidi** [IllinoisCogComp/saul#450]
(Re-running SRL experiments) Has anyone ran inference using a new Gurobi license? Running on Shelley, I get the following exceptions, and it comes randomly in different places when running inference, while the same thing was running before.  Or related to Gurobi version (new license with old version?), or new Shelley transfer to Ubuntu?  Any idea? 

```scala
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8c3a837e33, pid=14795, tid=0x00007f8d04652700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b14) (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libgurobi60.so+0x386e33]  GRBgetusername+0x33
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

**Comment by kordjamshidi** [comment]
Same problem using `austen`.

**Comment by bhargav** [comment]
Can you see if Gurobi is installed and environment variables setup correctly?

Quick way to test is to see if the command `gurobi_cl` works. I have to update the Gurobi jar dependency to `6.5` to get it to work.

**Comment by kordjamshidi** [comment]
of course, the variables are set correctly. It is even running many iterations of inference. I am trying `bronte` now, to see if it related to Ubuntu and Gurobi. The new Gurobi version is 7.01.

**Comment by kordjamshidi** [comment]
OMG. what is this `gurobi_lc`? it throws error: 
`./gurobi_cl: error while loading shared libraries: libgurobi60.so: cannot open shared object file: No such file or directory`

**Comment by kordjamshidi** [comment]
For records: New licence with new version and deploy the version to m2repo, solved the problem.
