### ISSUE TITLE
[SpRL] data format

### ISSUE THREAD

**Issue by EloiZ** [IllinoisCogComp/saul#466]
Hello,
I'm willing to run the example of the SpRL task. 
However, it requires training or testing data (in the folder "saul/saul-examples/data/SpRL/2013/IAPR TC-12/gold")

Can you please specify how this folder should be organized?

Thanks a lot in advance for your consideration,

**Comment by kordjamshidi** [comment]
Hi @EloiZ , The code that you are pointing at uses the data that can be downloaded from here http://www.cs.tulane.edu/~pkordjam/SpRL.htm, find Download SpRL-2013, on that page.

**Comment by EloiZ** [comment]
Thanks a lot for your answer! :)

**Comment by PattyBG** [comment]
Hi :)

I am also working on the SpRL task. I downloaded the data but I still have the following issue: 

[error] Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1,5 sec].
[error] Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0,7 sec].

What should I do ? Where can I download this files and where should I put them in my path ? 
Thanks a lot for your help.
