### ISSUE TITLE
Using Mixed Properties By Learners

### ISSUE THREAD

**Issue by kordjamshidi** [IllinoisCogComp/saul#69]
The main goal of defining properties in the data model is that we can later just tell the learning models to use the property-name + property-value somehow (depending on the type of the property) as their features to generate feature vectors and lexicons. However, if the type of the properties are not consistent we will have a problem, for example, to ask the learner to use both real and discrete properties. We need to take care of this issue when finishing with the data model.

**Comment by kordjamshidi** [comment]
Are we able to use mixed features? did anyone have had a chance to test this and address this issue?

**Comment by danyaljj** [comment]
An undergrad working on it. Not sure how long it will take though.

**Comment by kordjamshidi** [comment]
When he/she has started?

**Comment by kordjamshidi** [comment]
Also, is this issue 'is' an issue? because in terms of compilation and running, it seems everything runs well.

**Comment by danyaljj** [comment]
He started last week. 

I didn't get your 2nd point.

**Comment by kordjamshidi** [comment]
I mean what happens if we just define all kinds of properties in the data-model where some of them are real and some discrete? Do we have any evidence that this is not working properly in the current Saul.

**Comment by danyaljj** [comment]
As far as I remember, I have tried such a mixture of real and discrete properties and it doesn't work.

**Comment by kordjamshidi** [comment]
As far as I see, it works in terms of running and giving meaningful results but, I can not make sure if these are the results we are supposed to get and I am not sure if all features go through correctly.

**Comment by danyaljj** [comment]
In my experience, adding real-valued features significantly ruins the performance (compared to the case when we have a only discrete features)

**Comment by kordjamshidi** [comment]
@danyaljj: we have worked on this issue with various toy examples, what we conclude is that the discrepancy of the results is because when you add more features (here the real ones) you need more training iterations. It would be great if you could recover the test that you mentioned above and try it with more training iterations, hopefully, you could confirm. It seems to us that the mixed features just work fine. They are all treated as real features (1.0, 0.0 for the discrete case), correctly.

**Comment by danyaljj** [comment]
Thanks for pointing this out.

@Slash0BZ: let's verify this hypothesis.

**Comment by danyaljj** [comment]
@kordjamshidi I think you were right. Here is a the comprehensive results on our experiments: 

https://github.com/IllinoisCogComp/lbjava/wiki/On-behavior-of-lbjava-when-dealing-with-real-valued-features.

**Comment by kordjamshidi** [comment]
ok, great.
