### ISSUE TITLE
What should we do with train and test inside nodes? 

### ISSUE THREAD

**Issue by kordjamshidi** [IllinoisCogComp/saul#82]
Train is ok still but the testWith body now has been commented out, hence we can not test classifiers.  So we need to decide about the way we want to treat the train and test collections. Should we keep them inside the nodes still? In this case should we bring the functionality back with the testWith and just rename the function to `populateTestNodes` for example?

**Comment by danyaljj** [comment]
I think this issue is resolved now ...
