### ISSUE TITLE
pathTohead in constrained classifiers 

### ISSUE THREAD

**Issue by kordjamshidi** [IllinoisCogComp/saul#87]
See the way we find the global object (which gives access to all variables in the main ILP objective) from  a local object (one specific variable in the objective) in the constrained classifier structure: 
https://github.com/IllinoisCogComp/saul/blob/master/saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala#L32-L42

See the example and the way set this access before: 

https://github.com/IllinoisCogComp/saul/blob/master/saul-examples/src/main/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/EntityMentionRelation/Classifiers.scala#L108-L113

It means now, we should specify the edge from conllRawToken to the connected conllRelation and we should be able to filter if more than one conllRelation is connected to this conllRawToken. 
Can we refine this in the current edition?

**Comment by danyaljj** [comment]
@kordjamshidi ?

**Comment by kordjamshidi** [comment]
Jaaa!
