### ISSUE TITLE
Storing properties

### ISSUE THREAD

**Issue by kordjamshidi** [IllinoisCogComp/saul#98]
For the moment the properties are a computed when they are called.  However, each property can be a complex graph query and to reduce the computational cost we better to store the properties and avoid recomputing them. This is also relevant to the serialization/deserialization of the graph on which @Gary is working.

**Comment by danyaljj** [comment]
@kordjamshidi I think this is finished; right?

**Comment by kordjamshidi** [comment]
@danyaljj : how we can cache specific properties, like labels of the classifiers? I guess you had this for the pos-tagging.

**Comment by danyaljj** [comment]
There is a property-specific caching which is explained here: https://github.com/IllinoisCogComp/saul/blob/master/saul-core/doc/CONCEPTUALSTRUCTURE.md#defining-properties

**Comment by kordjamshidi** [comment]
This is great, solved my problem!

**Comment by danyaljj** [comment]
Re-open if this is not finished yet.
